---

- name: "APT - Add Docker GPG key"
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "APT - Add Docker repository"
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker


- name: "APT - install 'docker-ce'"
  become: true
  apt:
    name: "docker-ce"
    update_cache: yes