---
- name: Install i3-gaps
  become: yes
  pacman: name="i3-gaps" state="present"

- name: Install i3exit
  become: yes
  pacman: name="i3exit" state="present"

- name: Install i3-lock
  become: yes
  pacman: name="i3lock" state="present"

- name: Install i3-blocks
  yaourt: name="i3blocks" state="present"
  become: yes
  become_user: "{{ primary_non_root_user }}"
