---

# git setup
- name: Setup default git configuraiton
  become: no
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "Rowan Self" }
    - {name: "user.email", value: "rowan.self@gmail.com" }
