---
- name: install base packages
  apt: 
    name: ['git', 'zsh', 'synaptic', 'guake', 'compton', 'numix-icon-theme-circle', 'arc-theme', 'software-properties-common', 'curl', 'python3-pip'] 
    state: "present"

