---
- name: install dependencies (apt)
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
    state: present

- name: install key (apt)
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: install VS Code (apt)
  apt:
    name: "code{{ (visual_studio_code_version != '') | ternary('=' + visual_studio_code_version, '') }}"
    state: present
